default: 30
# "KEY_ESC:1": 30
# "KEY_1:2": 30
# "KEY_2:3": 30
# "KEY_3:4": 30
# "KEY_4:5": 30
# "KEY_5:6": 30
# "KEY_6:7": 30
# "KEY_7:8": 30
# "KEY_8:9": 30
# "KEY_9:10": 30
# "KEY_0:11": 30
# "KEY_MINUS:12": 30
# "KEY_EQUAL:13": 30
# "KEY_BACKSPACE:14": 30
# "KEY_TAB:15": 30
# "KEY_Q:16": 30
# "KEY_W:17": 30
# "KEY_E:18": 30
# "KEY_R:19": 30
# "KEY_T:20": 30
# "KEY_Y:21": 30
# "KEY_U:22": 30
"KEY_I:23": 50
# "KEY_O:24": 30
"KEY_P:25": 50
# "KEY_LEFTBRACE:26": 30
# "KEY_RIGHTBRACE:27": 30
# "KEY_ENTER:28": 30
# "KEY_LEFTCTRL:29": 30
# "KEY_A:30": 30
# "KEY_S:31": 30
# "KEY_D:32": 30
# "KEY_F:33": 30
# "KEY_G:34": 30
# "KEY_H:35": 30
# "KEY_J:36": 30
# "KEY_K:37": 30
# "KEY_L:38": 30
# "KEY_SEMICOLON:39": 30
# "KEY_APOSTROPHE:40": 30
# "KEY_GRAVE:41": 30
# "KEY_LEFTSHIFT:42": 30
# "KEY_BACKSLASH:43": 30
# "KEY_Z:44": 30
# "KEY_X:45": 30
"KEY_C:46": 75
# "KEY_V:47": 30
# "KEY_B:48": 30
# "KEY_N:49": 30
"KEY_M:50": 60
# "KEY_COMMA:51": 30
# "KEY_DOT:52": 30
# "KEY_SLASH:53": 30
# "KEY_RIGHTSHIFT:54": 30
# "KEY_KPASTERISK:55": 30
# "KEY_LEFTALT:56": 30
# "KEY_SPACE:57": 30
# "KEY_CAPSLOCK:58": 30
# "KEY_F1:59": 30
# "KEY_F2:60": 30
# "KEY_F3:61": 30
# "KEY_F4:62": 30
# "KEY_F5:63": 30
# "KEY_F6:64": 30
# "KEY_F7:65": 30
# "KEY_F8:66": 30
# "KEY_F9:67": 30
# "KEY_F10:68": 30
# "KEY_NUMLOCK:69": 30
# "KEY_SCROLLLOCK:70": 30
# "KEY_KP7:71": 30
# "KEY_KP8:72": 30
# "KEY_KP9:73": 30
# "KEY_KPMINUS:74": 30
# "KEY_KP4:75": 30
# "KEY_KP5:76": 30
# "KEY_KP6:77": 30
# "KEY_KPPLUS:78": 30
# "KEY_KP1:79": 30
# "KEY_KP2:80": 30
# "KEY_KP3:81": 30
# "KEY_KP0:82": 30
# "KEY_KPDOT:83": 30
# "KEY_ZENKAKUHANKAKU:85": 30
# "KEY_102ND:86": 30
# "KEY_F11:87": 30
# "KEY_F12:88": 30
# "KEY_RO:89": 30
# "KEY_KATAKANA:90": 30
# "KEY_HIRAGANA:91": 30
# "KEY_HENKAN:92": 30
# "KEY_KATAKANAHIRAGANA:93": 30
# "KEY_MUHENKAN:94": 30
# "KEY_KPJPCOMMA:95": 30
# "KEY_KPENTER:96": 30
# "KEY_RIGHTCTRL:97": 30
# "KEY_KPSLASH:98": 30
# "KEY_SYSRQ:99": 30
# "KEY_RIGHTALT:100": 30
# "KEY_HOME:102": 30
# "KEY_UP:103": 30
# "KEY_PAGEUP:104": 30
# "KEY_LEFT:105": 30
# "KEY_RIGHT:106": 30
# "KEY_END:107": 30
# "KEY_DOWN:108": 30
# "KEY_PAGEDOWN:109": 30
# "KEY_INSERT:110": 30
# "KEY_DELETE:111": 30
# "KEY_MUTE:113": 30
# "KEY_VOLUMEDOWN:114": 30
# "KEY_VOLUMEUP:115": 30
# "KEY_POWER:116": 30
# "KEY_KPEQUAL:117": 30
# "KEY_PAUSE:119": 30
# "KEY_KPCOMMA:121": 30
# "KEY_HANGEUL:122": 30
# "KEY_HANJA:123": 30
# "KEY_YEN:124": 30
# "KEY_LEFTMETA:125": 30
# "KEY_RIGHTMETA:126": 30
# "KEY_COMPOSE:127": 30
# "KEY_STOP:128": 30
# "KEY_AGAIN:129": 30
# "KEY_PROPS:130": 30
# "KEY_UNDO:131": 30
# "KEY_FRONT:132": 30
# "KEY_COPY:133": 30
# "KEY_OPEN:134": 30
# "KEY_PASTE:135": 30
# "KEY_FIND:136": 30
# "KEY_CUT:137": 30
# "KEY_HELP:138": 30
# "KEY_CALC:140": 30
# "KEY_SLEEP:142": 30
# "KEY_WWW:150": 30
# "KEY_COFFEE:152": 30
# "KEY_BACK:158": 30
# "KEY_FORWARD:159": 30
# "KEY_EJECTCD:161": 30
# "KEY_NEXTSONG:163": 30
# "KEY_PLAYPAUSE:164": 30
# "KEY_PREVIOUSSONG:165": 30
# "KEY_STOPCD:166": 30
# "KEY_REFRESH:173": 30
# "KEY_EDIT:176": 30
# "KEY_SCROLLUP:177": 30
# "KEY_SCROLLDOWN:178": 30
# "KEY_KPLEFTPAREN:179": 30
# "KEY_KPRIGHTPAREN:180": 30
# "KEY_F13:183": 30
# "KEY_F14:184": 30
# "KEY_F15:185": 30
# "KEY_F16:186": 30
# "KEY_F17:187": 30
# "KEY_F18:188": 30
# "KEY_F19:189": 30
# "KEY_F20:190": 30
# "KEY_F21:191": 30
# "KEY_F22:192": 30
# "KEY_F23:193": 30
# "KEY_F24:194": 30
# "KEY_UNKNOWN:240": 30
